import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./GlobalProviders";

const inter = Inter({ subsets: ["latin"] });
GlobalProvider;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <GlobalProvider>
        <body className={inter.className}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
