import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./GlobalProviders";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });
GlobalProvider;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, ...props }) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={inter.className}>
          {" "}
          <NextThemesProvider
            {...props}
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </NextThemesProvider>
        </body>
      </GlobalProvider>
    </html>
  );
}
